### ISSUE TITLE
Bug report - missing_cluster_on_endpoint_on_zcl_node

### ISSUE THREAD

**Issue by riisling** [JohanBendz/com.tuya.zigbee#715]
### Describe the bug

> A clear and concise description of what the bug is.

Trying to add the device _TZE200_3towulqd to Homey.
The device is added, but the icon shows a red exclamation mark.
The error code shown is "missing_cluster_on_endpoint_on_zcl_node" and the device doesen't work.

### To Reproduce

Add new device

### App and Homey version

> * What Homey version are you running? 
Homey Pro (Early 2023)
> * What version of Homey firmware do you use?
10.2.1
> * What version of the Tuya Zigbee App are you using?
0.2.23 Test

**Comment by JohanBendz** [comment]
Hi @riisling, please create a diagnostic report from the app and get back to me with the report id.

**Comment by riisling** [comment]
Hi @JohanBendz, the report code is fedc1854-2097-41bc-a406-6243eb694197

**Comment by maccyber** [comment]
Got the same message here with version 0.2.23 (test) when I try to add _TZE200_3towulqd

Report code: 35608291-5b5c-44b8-8a9a-1b51e4143217

[Interview](https://gist.github.com/maccyber/b3d960f84ea4c25606412d034ac9700e)

![image](https://github.com/JohanBendz/com.tuya.zigbee/assets/701351/3dd5841b-d795-4793-a193-6f4df7776cff)

**Comment by avanderwulp** [comment]
This is my report code : 0604a99f-be83-4fc2-a2a7-1b64b3ab2fd2 on Homey 2016.

**Comment by maccyber** [comment]
With my limited zigbee/homey experience, the problem seems to be that the device reports back `NOT_FOUND` status, when the [zigbee-clusters library](https://github.com/athombv/node-zigbee-clusters) expects a [`SUCCESS`](https://github.com/athombv/node-zigbee-clusters/blob/master/lib/Cluster.js#L531) status in the retrived reports.

```
2024-02-05T19:30:12.540Z [err] [ManagerDrivers] [Driver:motion_sensor_2] [Device:bce85342-a123-4739-88c5-f7dc080637f6] Error: configuring attribute reporting (endpoint: 1, cluster: iasZone) { zoneStatus: { minInterval: 65535, maxInterval: 0, minChange: 0 } } Error: NOT_FOUND
    at IASZoneCluster.configureReporting (/app/node_modules/zigbee-clusters/lib/Cluster.js:516:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async motion_sensor_2.onNodeInit (/app/drivers/motion_sensor_2/device.js:13:4)
    at async /app/node_modules/homey-zigbeedriver/lib/ZigBeeDevice.js:957:11
```

Why the device sends a NOT_FOUND status is not known to me, but i could also see successful reports:

```
  zigbee-clusters:cluster ep: 1, cl: iasZone (1280) configure reporting [
  {
    direction: 'reported',
    attributeId: 2,
    attributeDataType: 25,
    minInterval: 65535,
    maxInterval: 0
  }
  ```
  
  ```
  zigbee-clusters:cluster ep: 1, cl: powerConfiguration (1) configure reporting [
  {
    direction: 'reported',
    attributeId: 33,
    attributeDataType: 32,
    minInterval: 65535,
    maxInterval: 0,
    minChange: 0
  }
```

**Comment by JohanBendz** [comment]
Thanks guys, I found a typo and some code to fix! 😅 Next update after some sleep.

**Comment by maccyber** [comment]
I got my device to recognize events with this code snippet, but seems like _TZE200_3towulqd devices are behaving differently, based on the report that [this](https://github.com/JohanBendz/com.tuya.zigbee/pull/724) driver worked for some devices (it did not for me)

```js
const { ZigBeeDevice } = require('homey-zigbeedriver');
const TuyaSpecificCluster = require('../../lib/TuyaSpecificCluster');
const { Cluster } = require('zigbee-clusters');

Cluster.addCluster(TuyaSpecificCluster);

const dataPoints = {
    pir_state: 1,
    battery_percentage: 4,
    interval_time: 102,
    pir_sensitivity: 9,
    pir_time: 10,
    illuminance_value: 12
}

const dataTypes = {
    value: 2, // [ 4 byte value ]
    enum: 4, // [ 0-255 ]
};

const getDataValue = (dpValue) => {
    switch (dpValue.datatype) {
        case dataTypes.value:
            return parseInt(dpValue.data.toString('hex'), 16);
        case dataTypes.enum:
            return dpValue.data[0];
         default:
           return dpValue;
    }
}

class motion_sensor_2 extends ZigBeeDevice {
    async onNodeInit({ zclNode }) {
        this.enableDebug();
        this.printNode();

        zclNode.endpoints[1].clusters[TuyaSpecificCluster.NAME]
            .on('response', this.updateData.bind(this))
    }

    updateData(data) {
        const value = getDataValue(data);
        this.log(`DP: ${data.dp} - Value: ${value}`)
        switch (data.dp) {
            case dataPoints.pir_state:
                const motion = value === 0
                this.log(`Motion status: ${motion}`);
                this.setCapabilityValue('alarm_motion', motion).catch(this.error);
                break;
            case dataPoints.illuminance_value:
                this.log(`Illuminance: ${value}`);
                this.setCapabilityValue('measure_luminance', value).catch(this.error);
                break;
            case dataPoints.battery_percentage:
                const batteryThreshold = this.getSetting('batteryThreshold') || 20;
                const batteryAlarm = value < batteryThreshold
                this.log(`Battery: ${value}`);
                this.setCapabilityValue('measure_battery', value).catch(this.error);
                this.setCapabilityValue('alarm_battery', batteryAlarm).catch(this.error);
                break;
            case dataPoints.pir_sensitivity:
                this.log(`PIR Sensitivity: ${value}`);
                break;
            case dataPoints.pir_time:
                this.log(`PIR Time: ${value}`);
                break;
            default:
                this.log(`Unrecognized DP: ${data.dp}`);
        }
    }
}

module.exports = motion_sensor_2;
```

driver.compose.json
```json
      "endpoints": {
        "1": {
          "clusters": [61184],
          "bindings": [61184]
        }

```

I have not implemented the setting of `interval_time`, `pir_sensitivity` or `pir_time` yet, but it could be implemented using [TuyaSpecificClusterDevice](https://github.com/JohanBendz/com.tuya.zigbee/blob/SDK3/lib/TuyaSpecificClusterDevice.js) presumably.

I can create a PR for it if this works for other people, but I have limited knowledge about zigbee and Homey.

In the debug console I see these datapoints: 12 (illuminance), 1 (pir state).
And on device init: 9 (pir sensitivity), 4 (battery level), 10 (pir time):

illuminance_value
```
  zigbee-clusters:cluster ep: 1, cl: tuya (61184) received frame response tuya.response {
  status: 0,
  transid: 27,
  dp: 12,
  datatype: 2,
  length: 4,
  data: <Buffer 00 00 00 0a>
}
```

pir_state
```
  zigbee-clusters:cluster ep: 1, cl: tuya (61184) received frame response tuya.response {
  status: 0,
  transid: 30,
  dp: 1,
  datatype: 4,
  length: 1,
  data: <Buffer 00>
 ```
 
 pir_sensitivity
 ```
   zigbee-clusters:cluster ep: 1, cl: tuya (61184) received frame response tuya.response {
  status: 0,
  transid: 23,
  dp: 9,
  datatype: 4,
  length: 1,
  data: <Buffer 02>
```

battery_percentage
```
  zigbee-clusters:cluster ep: 1, cl: tuya (61184) received frame response tuya.response {
  status: 0,
  transid: 21,
  dp: 4,
  datatype: 2,
  length: 4,
  data: <Buffer 00 00 00 64>
```

pir_time
```
  zigbee-clusters:cluster ep: 1, cl: tuya (61184) received frame response tuya.response {
  status: 0,
  transid: 24,
  dp: 10,
  datatype: 4,
  length: 1,
  data: <Buffer 00>
```
 
Here is a link to information about the data points I collected from the device: https://gist.github.com/maccyber/2c764e3a3c0ffc429e433e6530dfcc95

**Comment by abn** [comment]
@maccyber does #1027 fix the issue for you?

**Comment by dlnraja** [comment]
Hi! 👋

This device is **already supported** in [dlnraja/com.tuya.zigbee](https://github.com/dlnraja/com.tuya.zigbee) (Universal Tuya Zigbee fork) — **v5.11.14** with 138 drivers and 5,579+ fingerprints.

**Install the latest test version:**
https://homey.app/a/com.dlnraja.tuya.zigbee/test/

**Community forum for support:**
https://community.homey.app/t/app-pro-universal-tuya-zigbee-device-app-test/140352

After installing, delete and re-pair your device. If it still doesn't work, please share a **diagnostic report ID** and a **Homey Developer Tools interview** (https://tools.developer.homey.app).
