### ISSUE TITLE
Device Request - [Fingerbot Plus] - [_TZ3210_j4pdtz9v] / [TS0001]

### ISSUE THREAD

**Issue by AntondK88** [JohanBendz/com.tuya.zigbee#869]
### Device Information

- Device Name: `Fingerbot Plus`
- Device Model: `TS0001`
- Device Description: `Smart button pusher`
- Link to device image: [https://ae01.alicdn.com/kf/S6312345151f74c86bea6bf4cea58e694W.jpg]

### Device Interview

```json
{
    [
  "ids": {
    "modelId": "TS0001",
    "manufacturerName": "_TZ3210_j4pdtz9v"
  },
  "endpoints": {
    "ieeeAddress": "a4:c1:38:75:70:cc:f1:cd",
    "networkAddress": 4554,
    "modelId": "TS0001",
    "manufacturerName": "_TZ3210_j4pdtz9v",
    "endpointDescriptors": [
      {
        "status": "SUCCESS",
        "nwkAddrOfInterest": 4554,
        "_reserved": 18,
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 0,
        "applicationDeviceVersion": 0,
        "_reserved1": 1,
        "inputClusters": [
          6,
          61184,
          0
        ],
        "outputClusters": [
          25,
          10
        ]
      }
    ],
    "deviceType": "enddevice",
    "receiveWhenIdle": false,
    "capabilities": {
      "alternatePANCoordinator": false,
      "deviceType": false,
      "powerSourceMains": false,
      "receiveWhenIdle": false,
      "security": false,
      "allocateAddress": true
    },
    "extendedEndpointDescriptors": {
      "1": {
        "clusters": {
          "onOff": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "onOff",
                "value": false,
                "reportingConfiguration": {
                  "direction": "reported",
                  "attributeDataType": 16,
                  "minInterval": 60,
                  "maxInterval": 600,
                  "status": "SUCCESS"
                }
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2,
                "reportingConfiguration": {
                  "status": "NOT_FOUND",
                  "direction": "reported"
                }
              }
            ]
          },
          "basic": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 0,
                "name": "zclVersion",
                "value": 3
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 1,
                "name": "appVersion",
                "value": 82
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 2,
                "name": "stackVersion",
                "value": 0
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 3,
                "name": "hwVersion",
                "value": 1
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 4,
                "name": "manufacturerName",
                "value": "_TZ3210_j4pdtz9v"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 5,
                "name": "modelId",
                "value": "TS0001"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 6,
                "name": "dateCode",
                "value": ""
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 7,
                "name": "powerSource",
                "value": "battery"
              },
              {
                "acl": [
                  "readable",
                  "writable",
                  "reportable"
                ],
                "id": 65502
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 2
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65534,
                "name": "attributeReportingStatus",
                "value": "PENDING"
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65506
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 65507
              }
            ]
          }
        },
        "bindings": {
          "ota": {},
          "time": {
            "attributes": [
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ]
          }
        }
      }
    }
  }]
}
```

### Additional Comments:

AliExpress: 
https://nl.aliexpress.com/item/1005005715461824.html?dp=85bfd394d4c86b62be5ddf98c6ac75c2&af=1711154&cv=47843&afref=https%3A%2F%2Finfica.com&mall_affr=pr3&utm_source=admitad&utm_medium=cpa&utm_campaign=1711154&utm_content=47843&dp=85bfd394d4c86b62be5ddf98c6ac75c2&af=1711154&cv=47843&afref=https%3A%2F%2Finfica.com&mall_affr=pr3&utm_source=admitad&utm_medium=cpa&utm_campaign=1711154&utm_content=47843&aff_fcid=c3133567e78542e4b09e8f155714aada-1716398692656-03106-_ePNSNV&aff_fsk=_ePNSNV&aff_platform=portals-tool&sk=_ePNSNV&aff_trace_key=c3133567e78542e4b09e8f155714aada-1716398692656-03106-_ePNSNV&terminal_id=f627bc0a62f74842b20e7624b923b989&afSmartRedirect=y

**Comment by dalobalo** [comment]
Is the device added to the list and working with Homey?

**Comment by JohanBendz** [comment]
Support is added to next update. please report how it works @dalobalo @AntondK88 as I don't have it myself.

**Comment by JohanBendz** [comment]
Ping @AntondK88 @dalobalo

**Comment by dalobalo** [comment]
Thanks for the update. Still waiting for the device. Should arrive within a week or two. I will let you know how it goes

**Comment by dalobalo** [comment]
@JohanBendz So I am able to find and add both devices in homey, but no flows will work with ether of them. Also the battery status is unknown with a question mark. The device works if I press the button on the fingerbot itself. I have eliminated distance as an error source.

edit: 
Link to the unit 
https://a.aliexpress.com/_EzFgCml

**Comment by martinj** [comment]
Got the same device and have the same issue (running version v0.2.73). It pairs but i can't trigger the finger and battery status is not showing. 

Anything I can provide or help with to fix this?

**Comment by officekeys-nl** [comment]
I am testing it. But it is not working. I have VSC and will download the driver to see if I can alter the code

**Comment by officekeys-nl** [comment]
**I needed to remove "finger_bot_mode"  from capabilities in driver.compose.json because of the validation error:** 
App did not validate against level `debug`:
× Error: drivers.fingerbot invalid capability: finger_bot_mode
    at App._validate (C:\Users\kees\AppData\Roaming\npm\node_modules\homey\lib\App.js:132:13)
    at async App.runDocker (C:\Users\kees\AppData\Roaming\npm\node_modules\homey\lib\App.js:254:19)
    at async exports.handler (C:\Users\kees\AppData\Roaming\npm\node_modules\homey\bin\cmds\app\run.js:43:5) 

**After removing the following log was produced:**
2024-11-03T08:22:43.416Z [log] [myZigBeeTest] myZigBeeTest has been initialized
2024-11-03T08:22:43.997Z [log] [ManagerDrivers] [Driver:fingerbot] [Device:d0d6470f-d455-47eb-b91a-de3b506522b9] ZigBeeDevice has been initialized { firstInit: false, isSubDevice: false }
2024-11-03T08:22:43.998Z [log] [ManagerDrivers] [Driver:fingerbot] [Device:d0d6470f-d455-47eb-b91a-de3b506522b9] ------------------------------------------
2024-11-03T08:22:43.998Z [log] [ManagerDrivers] [Driver:fingerbot] [Device:d0d6470f-d455-47eb-b91a-de3b506522b9] Node: 5b812264-966f-4e23-a824-437b0d2aafab
2024-11-03T08:22:43.999Z [log] [ManagerDrivers] [Driver:fingerbot] [Device:d0d6470f-d455-47eb-b91a-de3b506522b9] - Receive when idle: false
2024-11-03T08:22:43.999Z [log] [ManagerDrivers] [Driver:fingerbot] [Device:d0d6470f-d455-47eb-b91a-de3b506522b9] - Endpoints: 1 
2024-11-03T08:22:43.999Z [log] [ManagerDrivers] [Driver:fingerbot] [Device:d0d6470f-d455-47eb-b91a-de3b506522b9] -- Clusters:   
2024-11-03T08:22:43.999Z [log] [ManagerDrivers] [Driver:fingerbot] [Device:d0d6470f-d455-47eb-b91a-de3b506522b9] --- basic      
2024-11-03T08:22:43.999Z [log] [ManagerDrivers] [Driver:fingerbot] [Device:d0d6470f-d455-47eb-b91a-de3b506522b9] --- onOff      
2024-11-03T08:22:43.999Z [log] [ManagerDrivers] [Driver:fingerbot] [Device:d0d6470f-d455-47eb-b91a-de3b506522b9] --- tuya       
2024-11-03T08:22:44.000Z [log] [ManagerDrivers] [Driver:fingerbot] [Device:d0d6470f-d455-47eb-b91a-de3b506522b9] ------------------------------------------
  zigbee-clusters:cluster ep: 1, cl: basic (0) read attributes [ 4, 0, 1, 5, 7, 65534 ]  +0ms
  zigbee-clusters:cluster ep: 1, cl: basic (0) send frame ZCLStandardHeader {
  frameControl: [],
  data: basic.readAttributes { attributes: [ 4, 0, 1, 5, 7, 65534 ] },
  cmdId: 0,
  trxSequenceNumber: 1
} +1ms
  zigbee-clusters:cluster ep: 1, cl: basic (0) received frame readAttributesStructured.response basic.readAttributesStructured.response {
  attributes: <Buffer 04 00 00 42 10 5f 54 5a 33 32 31 30 5f 6a 34 70 64 74 7a 39 76 00 00 00 20 03 01 00 00 20 48 05 00 00 42 06 54 53 30 30 30 31 07 00 00 30 03 fe ff 00 ... 2 more bytes>
} +556ms
  zigbee-clusters:cluster ep: 1, cl: basic (0) read attributes result {
  attributes: <Buffer 04 00 00 42 10 5f 54 5a 33 32 31 30 5f 6a 34 70 64 74 7a 39 76 00 00 00 20 03 01 00 00 20 48 05 00 00 42 06 54 53 30 30 30 31 07 00 00 30 03 fe ff 00 ... 2 more bytes>
} +1ms
2024-11-03T08:22:44.559Z [err] [ManagerDrivers] [Driver:fingerbot] [Device:d0d6470f-d455-47eb-b91a-de3b506522b9] Error: 'onNodeInit()' failed, reason: Error: Invalid Flow Card ID: finger_bot_mode
    at new FlowCard (/node_modules/@athombv/homey-apps-sdk-v3/lib/FlowCard.js:69:13)
    at new FlowCardAction (/node_modules/@athombv/homey-apps-sdk-v3/lib/FlowCardAction.js:20:5)
    at ManagerFlow.getActionCard (/node_modules/@athombv/homey-apps-sdk-v3/manager/flow.js:48:18)
    at FingerBotTuya.onNodeInit (/app/drivers/fingerbot/device.js:54:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/node_modules/homey-zigbeedriver/lib/ZigBeeDevice.js:949:11
2024-11-03T08:22:44.559Z [err] [ManagerDrivers] [Driver:fingerbot] [Device:d0d6470f-d455-47eb-b91a-de3b506522b9] Error: could not initialize node Error: Invalid Flow Card ID: finger_bot_mode
    at new FlowCard (/node_modules/@athombv/homey-apps-sdk-v3/lib/FlowCard.js:69:13)
    at new FlowCardAction (/node_modules/@athombv/homey-apps-sdk-v3/lib/FlowCardAction.js:20:5)
    at ManagerFlow.getActionCard (/node_modules/@athombv/homey-apps-sdk-v3/manager/flow.js:48:18)
    at FingerBotTuya.onNodeInit (/app/drivers/fingerbot/device.js:54:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/node_modules/homey-zigbeedriver/lib/ZigBeeDevice.js:949:11


**After on/off command I get the following log:**
  zigbee-clusters:cluster ep: 1, cl: tuya (61184) send frame ZCLStandardHeader {
  frameControl: [ 'clusterSpecific' ],
  data: tuya.datapoint {
    status: 0,
    transid: 0,
    dp: 1,
    datatype: 1,
    length: 1,
    data: <Buffer 00>
  },
  cmdId: 0,
  trxSequenceNumber: 1
} +2m
  zigbee-clusters:cluster ep: 1, cl: tuya (61184) received frame defaultResponse tuya.defaultResponse { cmdId: 0, status: 'SUCCESS' } +630ms
2024-11-03T08:24:53.906Z [log] [ManagerDrivers] [Driver:fingerbot] [Device:d0d6470f-d455-47eb-b91a-de3b506522b9] Finger Bot on/off set to false

**Comment by JohanBendz** [comment]
Ah, sorry about that. I released a driver to catch diagnostic reports for the unit, did not really expect it to work without adjustment.
A new version is on its way.

**Comment by slicke** [comment]
The driver can basically be replaced by a touch button (it works as intended with the "unknown zigbee" default driver. Could it be an idea to just remove the driver and put a 1-gang switch driver for it?

**Comment by slicke** [comment]
I used the "plug" to make a working driver: https://github.com/JohanBendz/com.tuya.zigbee/pull/1065

**Comment by officekeys-nl** [comment]
Yes, that would be a good suggestion if that works. It worked before the device was added. I think I defined it as an unknown device

**Comment by slicke** [comment]
> Yes, that would be a good suggestion if that works. It worked before the device was added. I think I defined it as an unknown device

It does 😊I'm running on my PR and it works fine 😊

**Comment by ml0renz0** [comment]
I had only one FingerBot and it worked great but started failing when I added a second one: now I can't get none of them to work. I will turn the new one off and see if the first one works back again.

Given this behaviour I started thinking that maybe there was something wrong in the FingerBot's firmware that was fixed in a newer release.

I searched but didn't find documentation on how to do so from Home Assistant

**Comment by maesben** [comment]
Same behaviour as described above: pairs, but then cannot be controlled (except the physical button). If necessary, I can provide logs. 
Disabling the Tuya Zigbee app and adding as a generic Zigbee device does allow to trigger the fingerbot.

**Comment by officekeys-nl** [comment]
I created a driver in my local app that works without problems. I am happy to share that driver so it can be added to the Tuya Zigbee app, but I do not know how :(

**Comment by pkroeze** [comment]
Same behavior as described above: pairs, but then cannot be controlled (except the physical button) and the battery status is unknown.

**Comment by dalobalo** [comment]
Will there not be any further updates on this device? I have not seen any updates on the app since 12th October.. hope its not the case

**Comment by seimnseimn** [comment]
This comment is by no means a "hurry up" or anything similar. Quite the opposite: Thank you Johan for all your effort, it is very much appreciated.

The PR from shaarkys is surely meant well, but does not add any value to the "unsupported" zigbee device option. I assume the most wanted feature for the Fingerbot integration is to have the "click only" option.

I'm adding this comment for others to 👍🏻 for you to see how much this is wanted :-)

Have a nice day

**Comment by dlnraja** [comment]
Hi! 👋

This device is **already supported** in [dlnraja/com.tuya.zigbee](https://github.com/dlnraja/com.tuya.zigbee) (Universal Tuya Zigbee fork) — **v5.11.14** with 138 drivers and 5,579+ fingerprints.

**Install the latest test version:**
https://homey.app/a/com.dlnraja.tuya.zigbee/test/

**Community forum for support:**
https://community.homey.app/t/app-pro-universal-tuya-zigbee-device-app-test/140352

After installing, delete and re-pair your device. If it still doesn't work, please share a **diagnostic report ID** and a **Homey Developer Tools interview** (https://tools.developer.homey.app).

**Comment by officekeys-nl** [comment]
HI @dlnraja ,
Thanks for your response. I just tested your driver for this device, but it contains errors :(
When the device is installed with your driver, and I switch het on/on in homey, I get an error: Could not get device by id
I see that "id" is missing from driver.compose.json , but when I add it, the error is not solved. also, when I run the code locally from VSC on docker I get the following error:
[err] [ManagerDrivers] [Driver:fingerbot] Error Initializing Device: Error: Cannot find module '../../lib/tuya/TuyaZigbeeDevice'
Require stack:
- /app/drivers/fingerbot/device.js
- /node_modules/@athombv/homey-apps-sdk-v3/lib/Util.js
- /node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js
- /node_modules/@athombv/homey-apps-sdk-v3/homey.js
- /node_modules/@athombv/homey-apps-sdk-v3/index.js
- /homey-app-runner/lib/App.js
- /homey-app-runner/index.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1383:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1025:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1030:22)
    at Function._load (node:internal/modules/cjs/loader:1192:37)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:237:24)
    at Module.<anonymous> (node:internal/modules/cjs/loader:1463:12)
    at Module.homeyRequire [as require] (/node_modules/@athombv/homey-apps-sdk-v3/index.js:12:19)
    at require (node:internal/modules/helpers:147:16)
    at Object.<anonymous> (/app/drivers/fingerbot/device.js:3:26) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/drivers/fingerbot/device.js',
    '/node_modules/@athombv/homey-apps-sdk-v3/lib/Util.js',
    '/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js',
    '/node_modules/@athombv/homey-apps-sdk-v3/homey.js',
    '/node_modules/@athombv/homey-apps-sdk-v3/index.js',
    '/homey-app-runner/lib/App.js',
    '/homey-app-runner/index.js'
  ]
}

**Comment by dalobalo** [comment]
Im getting error "Missing Capability Listener: button.push" and "Missing Capability Listener: onoff"
**Reported the issue here:** https://github.com/dlnraja/com.tuya.zigbee/issues
